import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GU_Rich",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/logo.jpg" />
      </head>
      <body className={inter.className}>
        {children}
        <Toaster 
          position="top-center"
          toastOptions={{
            // Styling all toasts
            style: {
              background: '#1a1a3a',
              color: '#fff',
            },
            // Styling success toasts
            success: {
              duration: 4000,
              style: {
                border: '1px solid #F39C12',
              },
            },
            // Styling error toasts
            error: {
              duration: 4000,
              style: {
                border: '1px solid #ef4444',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
